@startuml
left to right direction

actor Usuario as User

rectangle "Sistema" {
  usecase "Iniciar Sesión" as UC1
  usecase "Registrarse" as UC2
  usecase "Ver " as UC3
  usecase "Editar " as UC4
  usecase "Eliminar " as UC5
  usecase "Navegar por Páginas" as UC6
}

User --> UC1
User --> UC2
UC1 --> UC6
UC2 --> UC6

UC6 --> UC4
UC6 --> UC5
UC6 --> UC3

@enduml
